### ISSUE TITLE
Print was left in release by accident

### ISSUE THREAD

**Issue by qwbarch** [qwbarch/2captcha-haskell#1]
https://github.com/qwbarch/2captcha-haskell/blob/7b091f68f28b063acf35013908f84e8b8db1dd5b/src/TwoCaptcha/Internal/Client.hs#L32

This shouldn't be here, will be removing this in the next release

**Comment by udaycruise2903** [comment]
@qwbarch You mean the whole line would be removed by you in the next release?

**Comment by qwbarch** [comment]
Yes. I'm looking to improve the library as well for the next release so I'm holding off on this small issue until I have more changes out

**Comment by qwbarch** [comment]
This package is deprecated in favour of [captcha-2captcha](https://hackage.haskell.org/package/captcha-2captcha)
